<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Backend\Block\Widget\Button
 */
?>
<?php if(($block->getLabel() != 'Hold') && ($block->getLabel() != 'Ship') && ($block->getLabel() != 'Create New Customer')){ ?>
<?php echo $block->getBeforeHtml(); ?>
<button <?php echo $block->getAttributesHtml(), $block->getUiId(); ?>>
    <span><?php echo $block->getLabel(); ?></span>
</button>
<?php echo $block->getAfterHtml(); ?>
<?php } ?>
