	<!--<div class="row">
		<div class="container">
			<section class="customer-logos slider">
				<div class="slide"><img src="<?php echo $this->getViewFileUrl('Magento_Newsletter::images/image1.png'); ?>" /></div>
				<div class="slide"><img src="<?php echo $this->getViewFileUrl('Magento_Newsletter::images/image2.png'); ?>" /></div>
				<div class="slide"><img src="<?php echo $this->getViewFileUrl('Magento_Newsletter::images/image3.png'); ?>" /></div>
				<div class="slide"><img src="<?php echo $this->getViewFileUrl('Magento_Newsletter::images/image4.png'); ?>" /></div>
				<div class="slide"><img src="<?php echo $this->getViewFileUrl('Magento_Newsletter::images/image5.png'); ?>" /></div>
				<div class="slide"><img src="<?php echo $this->getViewFileUrl('Magento_Newsletter::images/image6.png'); ?>" /></div>
				<div class="slide"><img src="<?php echo $this->getViewFileUrl('Magento_Newsletter::images/image7.png'); ?>" /></div>
				<div class="slide"><img src="<?php echo $this->getViewFileUrl('Magento_Newsletter::images/image8.png'); ?>" /></div>
			</section>
		</div>
	</div>

	<script type="text/javascript">
		$(document).ready(function(){
			$('.customer-logos').slick({
				slidesToShow: 6,
				slidesToScroll: 1,
				autoplay: true,
				autoplaySpeed: 1000,
				arrows: false,
				dots: false,
					pauseOnHover: false,
					responsive: [{
					breakpoint: 768,
					settings: {
						slidesToShow: 4
					}
				}, {
					breakpoint: 520,
					settings: {
						slidesToShow: 3
					}
				}]
			});
		});
	</script>-->