<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php if (is_array($block->getChildBlock('diagrams')->getTabsIds())) : ?>
<script>
require([
    'Magento_Ui/js/modal/alert',
    'prototype'
], function(alert){

window.changeDiagramsPeriod = function(periodObj) {
    periodParam = periodObj.value ? 'period/' + periodObj.value + '/' : '';
<?php foreach ($block->getChildBlock('diagrams')->getTabsIds() as $tabId): ?>
    ajaxBlockParam = 'block/tab_<?php /* @escapeNotVerified */ echo $tabId ?>/';
    ajaxBlockUrl = '<?php echo $block->getUrl('adminhtml/*/ajaxBlock', ['_current' => true, 'block' => '', 'period' => '']) ?>' + ajaxBlockParam + periodParam;
    new Ajax.Request(ajaxBlockUrl, {
        parameters: {isAjax: 'true', form_key: FORM_KEY},
        onSuccess: function(transport) {
            tabContentElementId = '<?php /* @escapeNotVerified */ echo $block->getChildBlock('diagrams')->getId() ?>_<?php /* @escapeNotVerified */ echo $tabId ?>_content';
            try {
                if (transport.responseText.isJSON()) {
                    var response = transport.responseText.evalJSON()
                    if (response.error) {
                        alert({
                            content: response.message
                        });
                    }
                    if(response.ajaxExpired && response.ajaxRedirect) {
                        setLocation(response.ajaxRedirect);
                    }
                } else {
                    $(tabContentElementId).update(transport.responseText);
                }
            }
            catch (e) {
                $(tabContentElementId).update(transport.responseText);
            }
        }
    });
<?php endforeach; ?>
  
</script>
<?php endif; ?>
<div class="dashboard-container row">
    <h1>Welcome To Delta Beverages</h1>
    
</div>
