<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>

<?php if (is_array($block->getChildBlock('diagrams')->getTabsIds())) : ?>
<script>
require([
    'Magento_Ui/js/modal/alert',
    'prototype'
], function(alert){

window.changeDiagramsPeriod = function(periodObj) {
    periodParam = periodObj.value ? 'period/' + periodObj.value + '/' : '';
<?php foreach ($block->getChildBlock('diagrams')->getTabsIds() as $tabId): ?>
    ajaxBlockParam = 'block/tab_<?php /* @escapeNotVerified */ echo $tabId ?>/';
    ajaxBlockUrl = '<?php echo $block->getUrl('adminhtml/*/ajaxBlock', ['_current' => true, 'block' => '', 'period' => '']) ?>' + ajaxBlockParam + periodParam;
    new Ajax.Request(ajaxBlockUrl, {
        parameters: {isAjax: 'true', form_key: FORM_KEY},
        onSuccess: function(transport) {
            tabContentElementId = '<?php /* @escapeNotVerified */ echo $block->getChildBlock('diagrams')->getId() ?>_<?php /* @escapeNotVerified */ echo $tabId ?>_content';
            try {
                if (transport.responseText.isJSON()) {
                    var response = transport.responseText.evalJSON()
                    if (response.error) {
                        alert({
                            content: response.message
                        });
                    }
                    if(response.ajaxExpired && response.ajaxRedirect) {
                        setLocation(response.ajaxRedirect);
                    }
                } else {
                    $(tabContentElementId).update(transport.responseText);
                }
            }
            catch (e) {
                $(tabContentElementId).update(transport.responseText);
            }
        }
    });
<?php endforeach; ?>
  
</script>
<?php endif; ?>
<div id="dash" class="dashboard-container row">
   <div id="admin-dashboard">
        <div class="jumbotron">
            <h1>Welcome To Delta Devarages</h1>
            <p id="admin-text">Delta Beverages Limited produces sorghum beer and carbonated soft drinks. The company operates in businesses, including lager beer, carbonated soft drinks, transportation and distribution, and non-carbonated soft drinks. It is also a franchise
                holder of coca-cola bottlers in Zimbabwe. The company is based in Harare, Zimbabwe. Delta Beverages Limited is a subsidiary of Delta Corp. &nbsp; &nbsp; Ltd.</p>
        </div>
    </div>
</div>
