<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?= /* @escapeNotVerified */ __('Order Information') ?></strong>
    </div>
    <div class="block-content">
        <table>
            <tr>
                
                <td>
                    <?php if (!$_order->getIsVirtual()): ?>
                        <strong class="box-title"><span><?= /* @escapeNotVerified */ __('Address') ?></span></strong>
                        <address><?= /* @escapeNotVerified */ $block->getFormattedAddress($_order->getShippingAddress()) ?></address>
                    <?php endif; ?>
                </td>

                <td>
                    <strong class="box-title">
                        <span><?= /* @escapeNotVerified */ __('Payment Method') ?></span>
                    </strong>
                    <div class="box-content">
                        <?= $block->getPaymentInfoHtml() ?>
                    </div>
                </td>
            </tr>
        </table>
    <?php if (!$_order->getIsVirtual()): ?>
        <div class="box box-order-shipping-address">
            <strong class="box-title"><span><?= /* @escapeNotVerified */ __('Address') ?></span></strong>
            <div class="box-content">
                <address><?= /* @escapeNotVerified */ $block->getFormattedAddress($_order->getShippingAddress()) ?></address>
            </div>
        </div>

      <!--  <div class="box box-order-shipping-method">
            <strong class="box-title">
                <span><?= /* @escapeNotVerified */ __('Shipping Method') ?></span>
            </strong>
            <div class="box-content">
            <?php if ($_order->getShippingDescription()): ?>
                <?= $block->escapeHtml($_order->getShippingDescription()) ?>
            <?php else: ?>
                <?= /* @escapeNotVerified */ __('No shipping information available') ?>
            <?php endif; ?>
            </div>
        </div> -->
    <?php endif; ?>

      <!--<div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?= /* @escapeNotVerified */ __('Billing Address') ?></span>
            </strong>
            <div class="box-content">
                <address><?= /* @escapeNotVerified */ $block->getFormattedAddress($_order->getBillingAddress()) ?></address>
            </div>
        </div> -->
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?= /* @escapeNotVerified */ __('Payment Method') ?></span>
            </strong>
            <div class="box-content">
                <?= $block->getPaymentInfoHtml() ?>
            </div>
        </div>

    </div>
</div>
<script type="text/javascript">
require(['domReady'], function (domReady) { 
    domReady(function () { 
        //This function is called once the DOM is ready. 
        //It will be safe to query the DOM and manipulate 
        //DOM nodes in this function.
        /*console.info('The DOM is ready before I happen');
        var payment_method = document.getElementsByTagName("dl");//.getElementsByClassName("payment-method"); 
        payment_method.style.display = 'none';*/
    }); 
});
/*
define(['domReady!'], function () { 
    console.info('The DOM is ready before I happen');
});
require(["jQuery321"], function(){
    require(["bootstrap3"], function(){
            require(["main"], function(){
        });
    });
});*/
</script>