<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="actions requisition-view-links">
    <a class="action print"
       href="<?= /* @noEscape */ $block->getPrintUrl() ?>"
       data-mobile-label="<?= $block->escapeHtml(__('Print')) ?>"
       target="_blank">
        <span><?= $block->escapeHtml(__('Print')) ?></span>
    </a>
</div>
