<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<div class="bootstrap-iso">
<link rel="stylesheet" type="text/css" href="<?php echo '../../../../../resources/bootstrap/css/bootstrap-iso.css';?>">
<!--<link rel="stylesheet" type="text/css" href="<?php echo  '../../../../../resources/bootstrap/css/bootstrap.css' ;?>">-->


<?php $_order = $block->getOrder() ?>
<?php $_giftMessage; ?>
<div class="table-wrapper order-items">
    <table class="data table table-order-items" id="my-orders-table" summary="<?php /* @escapeNotVerified */ echo __('Items Ordered') ?>">
        <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('Items Ordered') ?></caption>
        <thead>
            <tr>
                <th class="col name"><?php /* @escapeNotVerified */ echo __('Product Name') ?></th>
                <th class="col sku"><?php /* @escapeNotVerified */ echo __('SKU') ?></th>
                <th class="col price"><?php /* @escapeNotVerified */ echo __('Price') ?></th>
                <th class="col qty"><?php /* @escapeNotVerified */ echo __('Qty') ?></th>
                <th class="col subtotal"><?php /* @escapeNotVerified */ echo __('Subtotal') ?></th>
            </tr>
        </thead>
        <?php $_items = $_order->getItemsCollection(); ?>
        <?php $_index = 0; ?>
        <?php $_count = $_items->count(); ?>
        <?php $_giftMessage = ''?>
        <?php foreach ($_items as $_item): ?>
            <?php if ($_item->getParentItem()) {
    continue;
} ?>
            <tbody>
                <?php echo $block->getItemHtml($_item) ?>
                <?php if ($this->helper('Magento\GiftMessage\Helper\Message')->isMessagesAllowed('order_item', $_item) && $_item->getGiftMessageId()): ?>
                    <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($_item); ?>
                    <tr>
                        <td class="col options" colspan="5">
                            <a href="#"
                               id="order-item-gift-message-link-<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                               class="action show"
                               aria-controls="order-item-gift-message-<?php /* @escapeNotVerified */ echo $_item->getId() ?>"
                               data-item-id="<?php /* @escapeNotVerified */ echo $_item->getId() ?>">
                                <?php /* @escapeNotVerified */ echo __('Gift Message') ?>
                            </a>
                            <?php $_giftMessage = $this->helper('Magento\GiftMessage\Helper\Message')->getGiftMessageForEntity($_item); ?>
                            <div class="order-gift-message" id="order-item-gift-message-<?php /* @escapeNotVerified */ echo $_item->getId() ?>" role="region" aria-expanded="false" tabindex="-1">
                                <a href="#"
                                   title="<?php /* @escapeNotVerified */ echo __('Close') ?>"
                                   aria-controls="order-item-gift-message-<?php /* @escapeNotVerified */ echo $_item->getId()?>"
                                   data-item-id="<?php /* @escapeNotVerified */ echo $_item->getId()?>"
                                   class="action close">
                                    <?php /* @escapeNotVerified */ echo __('Close') ?>
                                </a>
                                <dl class="item-options">
                                    <dt class="item-sender"><strong class="label"><?php /* @escapeNotVerified */ echo __('From') ?></strong><?php echo $block->escapeHtml($_giftMessage->getSender()) ?></dt>
                                    <dt class="item-recipient"><strong class="label"><?php /* @escapeNotVerified */ echo __('To') ?></strong><?php echo $block->escapeHtml($_giftMessage->getRecipient()) ?></dt>
                                    <dd class="item-message"><?php /* @escapeNotVerified */ echo $this->helper('Magento\GiftMessage\Helper\Message')->getEscapedGiftMessage($_item) ?></dd>
                                </dl>
                            </div>
                        </td>
                    </tr>
                <?php endif ?>
            </tbody>
        <?php endforeach; ?>
        <tfoot>
            <?php echo $block->getChildHtml('order_totals') ?>
        </tfoot>
    </table>
    <form id="updateorderform" method="post" action="" >
      <table id="neworder" class="hidden fields additional deletableItem">
        <thead>
          <td>SKU</td>
          <td>Qty</td>
          <td></td>
        </thead>
        <tbody>
          <?php $i = 1;
               foreach ($block->getOrder()->getItemsCollection() as $singleitem) {
                echo "<tr class='form-group'>";
                echo "<td><input type='text' class='form-control' name='sku".$i."' value='".$singleitem->getSku()."'/></td>";
                echo "<td><input type='text' class='form-control' name='qty".$i."' value='".$singleitem->getQtyOrdered()."'/></td>";
                echo "<td><a id='".$i."' onclick='removerow(this.id)'>Remove<a/></td>";      
                echo "</tr>";
                $i++;
          }?>
        </tbody>
        <tfoot>
          <?php echo "<input class='hidden' type='text' id ='orderid' name='orderid' value='".$block->getOrder()->getId()."'/>"; ?>
          
        </tfoot>
      </table>
    </form>
</div>

<button id="addrowbtn" type="button" class="hidden btn btn-primary btn-md glyphicon glyphicon-plus" onclick="addnewrow()"> Add Row
</button>

<?php if ($_giftMessage): ?>
<script type="text/x-magento-init">
    {
        "a.action.show, a.action.close": {
            "giftMessage": {}
        }
    }
</script>
<?php endif; ?>

<!-- Button trigger modal -->
<button id="updateorder" type="button" class="hidden btn btn-primary btn-md glyphicon glyphicon-floppy-disk" onclick="sendupdatedorder()"> Update Order
</button>

<!-- Button trigger modal -->
<button id="edit" type="button" class="btn btn-primary btn-md glyphicon glyphicon-pencil" onclick="showTable()"> Edit Order
</button>

<!-- Button trigger modal -->
<button id="cancelorder" type="button" class="btn btn-primary btn-md glyphicon glyphicon-trash" data-toggle="modal" data-target="#myModal"> Cancel Order
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Order Confirmation</h4>
      </div>
      <div class="modal-body">
        <form id="cancelorderform" method="post" action="" >
          Are You Sure You Want To Cancel Order # 
          <?php 
            echo "<b><label>".$block->getOrder()->getRealOrderId()."</label></b>";
            echo "<input type='text' name='ordernumber' class='hidden' value='".$block->getOrder()->getRealOrderId()."'/>";  
          ?>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">No</button>
        <button type="button" class="btn btn-danger" onclick="cancelOrder()">Yes</button>
      </div>
    </div>
  </div>
</div>
</div>

<script type="text/javascript">
  require(["bootstrap3"], function(){
   });
</script>
<script type="text/javascript">
  require(["main"], function(){
   });
</script>
