<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php // @codingStandardsIgnoreFile ?>
<?php /** @var $block \Magento\Framework\View\Element\Template */ ?>
<!-- ko scope: 'company' -->
<div class="message company-warning _hidden" data-bind="css: { _hidden: !isCompanyBlocked() }">
<span>
<?php /* @noEscape */ echo __(
    'Your company account is blocked and you cannot place orders. ' .
    'If you have questions, please contact your company administrator.'
); ?>
</span>
</div>
<!-- /ko -->
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "company": {
                        "component": "Magento_Company/js/view/company",
                        "logoutUrl": "<?= $block->escapeUrl($block->getUrl('customer/account/logout')) ?>"
                    }
                }
            }
        }
    }
</script>
