<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * @var $block \Magento\Ui\Component\Control\Button
 */
?>
<?= $block->getBeforeHtml() ?>
<?php if($block->getLabel() != "Add New Company" && $block->getLabel() != "Go to Archive"){ ?>
<button <?= /* @escapeNotVerified */ $block->getAttributesHtml(), $block->getUiId() ?>>
    <span><?= /* @escapeNotVerified */ $block->getLabel() ?></span>
</button>
<?php } ?>
<?= $block->getAfterHtml() ?>
