<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>
    require(
        [
            'jquery'
        ],
        function($) {
            $(function() {
                // change company logo
                $('#maincontent > a.logo > img').attr('src', getSiteUrl() + 'resources/loginLogo.png');

                // change page title
                var newPageTitle = 'Print ' + $('h1.page-title span.base:first').html();
                $(document).attr("title", newPageTitle);

                // get order date
                var orderDate = $('#hiddenOrderDetails > div.order-date').html().replace('<strong>Created: </strong>', '');
                orderDate = orderDate.slice(0, orderDate.indexOf('(') - 1);
                $('#orderDate').html(': ' + orderDate);

                // get order number
                var orderNumber = $('#hiddenOrderDetails > h1 > span').html().replace('Order # ', '');
                $('#orderNumber').html(': ' + orderNumber);

                // get order status
                var orderStatus = $('#hiddenOrderDetails > span.order-status').html().toUpperCase();
                $('#orderStatus').html(': ' + orderStatus);

                //show formatted order details
                $('#orderDetails').show();

                // hide unformatted order details
                $('#hiddenOrderDetails').hide();

                var customerDetails = $('#orderInformationSection > address').html();
                $('#customerDetails').html(customerDetails);

                // hide order information section
                $('#orderInformationSection').hide();

                // align all amounts to the right 
                $(".amount").css("text-align", "right");

                // print the page
                window.print();
            });
        }
    );

    // function to return the site's base url
    // function getBaseUrl() {
    //     var re = new RegExp(/^.*\//);
    //     return re.exec(window.location.href);
    // }
    function getSiteUrl() {
        var slashIndex = getNthPosition(window.location.href, '/', 4);
        return window.location.href.substring(0, slashIndex) + '/';
    }

    function getNthPosition(string, subString, occurrence) {
        return string.split(subString, occurrence).join(subString).length;
    }
</script>
