<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<script>
    require(
        [
            'jquery'
        ],
        function($) {
            $(function() {
                // change page title
                var newPageTitle = 'Print ' + $('h1.page-title span.base:first').html();
                $(document).attr("title", newPageTitle);

                // align all amounts to the right 
                $(".amount").css("text-align", "right");

                // print the page
                window.print();
            });
        }
    );
</script>
