<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * @var $block \Magento\Theme\Block\Html\Title
 */
$cssClass = $block->getCssClass() ? ' ' . $block->getCssClass() : '';
$title = '';
if (trim($block->getPageHeading())) {
    $title = '<span class="base" data-ui-id="page-title-wrapper" ' .  $block->getAddBaseAttribute() . '>'
        . $block->escapeHtml($block->getPageHeading()) . '</span>';
}
?>
<?php if ($title): ?>
<table id="orderDetails" style="display: none;">
<!-- <table id="orderDetails"> -->
    <tr>
        <td width="30%" style="padding: 0;">
            <div class="order-details-items" style="padding: 0;">
                <table>
                    <tr>
                        <td style="padding-top: 2px; padding-bottom: 2px;" id="customerDetails">Customer details here</td>
                    </tr>
                </table>
            </div>
        </td>
        <td></td>
        <td width="40%" style="padding: 0;">
            <h3 style="text-align: center; margin: 0;">SALES ORDER</h3>
            <div class="order-details-items" style="padding: 0;">
                <table>
                    <tr>
                        <th style="padding-top: 2px; padding-bottom: 2px;">Date:</th>
                        <td style="padding-top: 2px; padding-bottom: 2px;" id="orderDate"></td>
                    </tr>
                    <tr>
                        <th style="padding-top: 2px; padding-bottom: 2px;">Order #:</th>
                        <td style="padding-top: 2px; padding-bottom: 2px;" id="orderNumber"></td>
                    </tr>
                </table>
            </div>
        </td>
    </tr>
</table>
<div class="page-title-wrapper<?= /* @escapeNotVerified */ $cssClass ?>">
    <h1 class="page-title"
        <?php if ($block->getId()): ?> id="<?= /* @escapeNotVerified */ $block->getId() ?>" <?php endif; ?>
        <?php if ($block->getAddBaseAttributeAria()): ?>
            aria-labelledby="<?= /* @escapeNotVerified */ $block->getAddBaseAttributeAria() ?>"
        <?php endif; ?>>
        <?= /* @escapeNotVerified */ $title ?>
    </h1>
    <?= $block->getChildHtml() ?>
</div>
<?php endif; ?>
