<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Top menu for store
 *
 * @var $block \Magento\Theme\Block\Html\Topmenu
 */
?>
<style type="text/css">

/*#proceed_to_checkout{
    margin-top: 50px;
}*/

</style>
<?php
$om = \Magento\Framework\App\ObjectManager::getInstance();
$helper = $om->create('Consnet\Api\Helper\Data'); 
$NAMESPACE_ID = $helper->getGeneralConfig('namespace_text');
$quote = $om->get('\Magento\Checkout\Model\Session')->getQuote();
$count = 0;//count($quote->getItemsCount());
foreach ($quote->getAllVisibleItems() as $items) {
    $count = $count + 1;
}
//isset($_SESSION['kunnr']) && 

$columnsLimit = $block->getColumnsLimit() ?: 0; ?>
<?php $_menu = $block->getHtml('level-top', 'submenu', $columnsLimit) ?>

<nav class="navigation" data-action="navigation">
    <ul data-mage-init='{"menu":{"responsive":true, "expanded":true, "position":{"my":"left top","at":"left bottom"}}}'>
        <?= /* @escapeNotVerified */ $_menu ?>
        <?= /* @escapeNotVerified */ $block->getChildHtml() ?>
        <?php if($count > 0){ ?>
        <li style="float:right; margin-top: 5px;" class="level0 nav-5 last level-top ui-menu-item" role="presentation">
            
        <a class="level-top ui-corner-all" tabindex="-1" role="menuitem">
                Cart: 
                <span id='itemcounter' class="counter-number"></span> 
                items
                <button type="button" class="action primary checkout"  id="proceed_to_checkout" style="">
                    CHECKOUT 
                </button>               
            </a>
        </li>
        <?php } ?>
    </ul>
</nav>

<?php echo "<form id='viewCartForm' action='http://".$NAMESPACE_ID."/erporder/Index/Index' method='post'>"; ?>
    <input type="text" id="view" value='1' class="hidden"/>
</form>

<script type="text/javascript">

var proceed = document.getElementById('proceed_to_checkout');
if(proceed != null){
    proceed.addEventListener("click", function () {
        var span = document.getElementById('itemcounter');
        if(span.textContent == null || span.textContent == '' || span.textContent == 'underfined'){
            console.log(span.textContent);
        }else{
            window.location = "<?php echo "http://".$NAMESPACE_ID."/checkout/ ";?>";
            /*require(['jquery'], function($){
                $('viewCartForm').submit(function (event){
                    console.log();
                });
            });*/
        }
    });
}    
</script>