<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php /** @var $block \Magento\Company\Block\Company\Management\Info */ ?>
<?php if (!$block->hasCustomerCompany()): ?>
    <div class="message info empty">
        <span><?= /* @noEscape */ __('You don\'t have a company account yet.') ?></span>
    </div>
    <?php if ($block->isAllowedRegister()): ?>
        <div class="actions-toolbar">
            <div class="primary">
                <a href="<?= $block->escapeUrl($block->getCreateCompanyAccountUrl()) ?>"
                   class="action create primary">
                    <span><?= /* @noEscape */ __('Create a Company Account') ?></span>
                </a>
            </div>
        </div>
    <?php endif; ?>
<?php endif; ?>
