<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
$modal_on = $block->getRegValue();

//die();

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Dashboard\Info $block */
?>
<?php if($modal_on){ ?>
 <div id="popup-mpdal" style="display:none;">
  <?php include ($block->getTemplateFile('Magento_Customer::accounts.phtml')); ?>
</div>
<?php } ?>

<style>
.modals-wrapper .modal-popup .modal-inner-wrap {
    width: 600px;
}
</style>


<div class="block block-dashboard-info">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Account Information - Represented Customer : '. $block->getCompany()->getData('STP_ID')))?></strong></div>
    <div class="block-content">
        <div class="box box-information">
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Contact Information')) ?></span>
            </strong>
            <div class="box-content">
                <p>
                    <?= $block->escapeHtml($block->getName()) ?><br>
                    <?= $block->escapeHtml($block->getCustomer()->getEmail()) ?><br>
                </p>
            </div>
            <div class="box-actions">
               <!-- <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/account/edit')) ?>">
                    <span><?= $block->escapeHtml(__('Edit')) ?></span>
                </a> -->
                <a href="<?= $block->escapeUrl($block->getChangePasswordUrl()) ?>" class="action change-password">
                    <?= $block->escapeHtml(__('Change Password')) ?>
                </a>
            </div>
        </div>
        <?php if ( 0 > 1): ?>
            <div class="box box-newsletter">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Newsletters')) ?></span>
                </strong>
                <div class="box-content">
                    <p>
                        <?php if ($block->getIsSubscribed()): ?>
                            <?= $block->escapeHtml(__('You are subscribed to "General Subscription".')) ?>
                        <?php else: ?>
                            <?= $block->escapeHtml(__('You aren\'t subscribed to our newsletter.')) ?>
                        <?php endif; ?>
                    </p>
                    <?php /* Extensions placeholder */ ?>
                    <?= $block->getChildHtml('customer.account.dashboard.info.extra') ?>
                </div>
                <div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('newsletter/manage')) ?>"><span><?= $block->escapeHtml(__('Edit')) ?></span></a>
                </div>
            </div>
        <?php endif; ?>
    </div>
</div>
<script>
<?php if($modal_on){ ?>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                title : 'Select an account ',

                innerScroll: true,
                buttons: [{
                    text: $.mage.__(' Close '),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };



            var popup = modal(options, $('#popup-mpdal'));

            $("#popup-mpdal").modal("openModal");

            $("#click-me").on('click',function(){
              //  $("#popup-mpdal").modal("openModal");
            });

        }
    );
    <?php } ?>
</script>
