<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Adminhtml\Order\View\Info */ ?>
<?php $_order = $block->getOrder() ?>
<?php
$orderAdminDate = $block->formatDate(
    $block->getOrderAdminDate($_order->getCreatedAt()),
    \IntlDateFormatter::MEDIUM,
    true
);
$orderStoreDate = $block->formatDate(
    $_order->getCreatedAt(),
    \IntlDateFormatter::MEDIUM,
    true,
    $block->getTimezoneForStore($_order->getStore())
);
?>                       

<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Order & Account Information') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <?php /* Order Information */?>
            <?php if ($_order->getEmailSent()):
                $_email = __('The order confirmation email was sent');  
            else:
                $_email = __('The order confirmation email is not sent');
            endif; ?>
            <div class="admin__page-section-item-title">
                <span class="title">
                    <?php if ($block->getNoUseOrderLink()): ?>
                     <?php		    
							//Custom ERP Order Number
							$om = \Magento\Framework\App\ObjectManager::getInstance();
							$resources = $om->get('Magento\Framework\App\ResourceConnection');
							$connection = $resources->getConnection();
							
							        $query = "SELECT `erpOrderId` FROM `erp_magento` WHERE `magOrderId` = '".$_order->getRealOrderId()."'";
							        $erporder =  $connection->fetchRow($query)['erpOrderId'];
							//End /* @escapeNotVerified */ /*$_order->getStatusLabel()*/ id="order_status"
							?>
                      <!--  <?php /* @escapeNotVerified */ echo __('Order # %1', $_order->getRealOrderId()) ?> -->
                             <?php /* @escapeNotVerified */ echo __('Order Information', $_order->getData('DELIVERY_DATE')/*$erporder*/) ?> 
                        <!--(<span><?php /* @escapeNotVerified */ echo $_email ?></span>)-->
                    <?php else: ?>
                        <a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order->getId()) ?>"><?php /* @escapeNotVerified */ echo __('Order # %1', $_order->getRealOrderId()) ?></a>
                        <span><!--(<?php /* @escapeNotVerified */ echo $_email ?>)--></span>
                    <?php endif; ?>
                </span>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                <tr>
                    <th><?php /* @escapeNotVerified */ echo __('Order Date') ?></th>
                    <td><?php /* @escapeNotVerified */ echo $orderAdminDate ?></td>
                </tr>
                <?php if ($orderAdminDate != $orderStoreDate):?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __(
                                'Order Date (%1)',
                                $block->getTimezoneForStore($_order->getStore())
                            ) ?></th>
                        <td><?php /* @escapeNotVerified */ echo $orderStoreDate ?></td>
                    </tr>
                <?php endif;?>
                <tr>
                    <th><?php /* @escapeNotVerified */ echo __('Delivery Date ') ?></th>
							<?php		    
							//Custom ERP Order Number
							$om = \Magento\Framework\App\ObjectManager::getInstance();
							$resources = $om->get('Magento\Framework\App\ResourceConnection');
							$connection = $resources->getConnection();
							
                            $query = "SELECT `erpOrderId` FROM `erp_magento` WHERE `magOrderId` = '".$_order->getRealOrderId()."'";
                            $erporder =  $connection->fetchRow($query)['erpOrderId'];
                            
                            $DBdate = $_order->getData('DELIVERY_DATE');
                            $delivery_date = substr($DBdate, 0,2).'/'.substr($DBdate, 2,2).'/'.substr($DBdate, 3);
                            
                            $mageorder = $om->create('\Consnet\Erporder\Helper\MageOrder');
                            $realOrderId = $_order->getRealOrderId();

                            $status = $order->getStatus();
                            
                            if($status !== 'canceled' || $status !== 'complete'){
                                $ecc_status = $mageorder->get_ecc_order_status($realOrderId);                    
                                if($status !== $ecc_status){
                                        switch ($ecc_status) {
                                            case "pending":
                                                $_order->setStatus(\Magento\Sales\Model\Order::STATE_PENDING);
                                                $_order->setState(\Magento\Sales\Model\Order::STATE_PENDING);
                                                //pending
                                                break;                        
                                            case "processing":
                                                $_order->setStatus(\Magento\Sales\Model\Order::STATE_PROCESSING);
                                                $_order->setState(\Magento\Sales\Model\Order::STATE_PROCESSING);
                                                $ecc_status = 'updated';
                                                //processing
                                                break;                        
                                            case "canceled":
                                                $_order->setStatus(\Magento\Sales\Model\Order::STATE_CANCELED);
                                                $_order->setState(\Magento\Sales\Model\Order::STATE_CANCELED);
                                                $ecc_status = 'updated';
                                                //canceled
                                                break;
                                            case "complete":
                                                $_order->setStatus(\Magento\Sales\Model\Order::STATE_COMPLETE);
                                                $_order->setState(\Magento\Sales\Model\Order::STATE_COMPLETE);
                                                $ecc_status = 'updated';
                                                //complete
                                                break;
                                        }$_order->save();   
                                    Header("Refresh:0");//print_r($ecc_status);
                                }
                            }
                            
							?>
                    <td><span><?php echo $delivery_date/*$erporder*/; ?></span></td>
                </tr>
                <?php echo $block->getChildHtml(); ?>
                <?php if ($block->isSingleStoreMode() == false):?>
                    <!--<tr>
                        <th><?php /* @escapeNotVerified */ echo __('Purchased From') ?></th>
                        <td><?php /* @escapeNotVerified */ echo $block->getOrderStoreName() ?></td>
                    </tr>-->
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Status') ?></th>
                        <td><?php /* @escapeNotVerified */ echo $_order->getStatus() ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getRelationChildId()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Link to the New Order') ?></th>
                        <td><a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order->getRelationChildId()) ?>">
                                <?php /* @escapeNotVerified */ echo $_order->getRelationChildRealId() ?>
                            </a></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getRelationParentId()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Link to the Previous Order') ?></th>
                        <td><a href="<?php /* @escapeNotVerified */ echo $block->getViewUrl($_order->getRelationParentId()) ?>">
                                <?php /* @escapeNotVerified */ echo $_order->getRelationParentRealId() ?>
                            </a></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getRemoteIp() && $block->shouldDisplayCustomerIp()): ?>
                    <!--<tr>
                        <th><?php /* @escapeNotVerified */ echo __('Placed from IP') ?></th>
                        <td><?php /* @escapeNotVerified */ echo $_order->getRemoteIp(); echo($_order->getXForwardedFor()) ? ' (' . $block->escapeHtml($_order->getXForwardedFor()) . ')' : ''; ?></td>
                    </tr>-->
                <?php endif; ?>
                <?php if ($_order->getGlobalCurrencyCode() != $_order->getBaseCurrencyCode()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('%1 / %2 rate:', $_order->getGlobalCurrencyCode(), $_order->getBaseCurrencyCode()) ?></th>
                        <td><?php /* @escapeNotVerified */ echo $_order->getBaseToGlobalRate() ?></td>
                    </tr>
                <?php endif; ?>
                <?php if ($_order->getBaseCurrencyCode() != $_order->getOrderCurrencyCode()): ?>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('%1 / %2 rate:', $_order->getOrderCurrencyCode(), $_order->getBaseCurrencyCode()) ?></th>
                        <th><?php /* @escapeNotVerified */ echo $_order->getBaseToOrderRate() ?></th>
                    </tr>
                <?php endif; ?>
            </table>
            </div>
        </div>

        <div class="admin__page-section-item order-account-information">
            <?php /* Account Information */?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Account Information') ?></span>
                <div class="actions"><?php /* @escapeNotVerified */ echo $block->getAccountEditLink()?></div>
            </div>
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-account-information-table">
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Customer Name') ?></th>
                        <td>
                            <?php if ($_customerUrl = $block->getCustomerViewUrl()) : ?>
                                <a href="<?php /* @escapeNotVerified */ echo $_customerUrl ?>" target="_blank">
                                    <span><?php echo $block->escapeHtml($_order->getCustomerName()) ?></span>
                                </a>
                            <?php else: ?>
                                <?php echo $block->escapeHtml($_order->getCustomerName()) ?>
                            <?php endif; ?>
                        </td>
                    </tr>
                    <tr>
                        <th><?php /* @escapeNotVerified */ echo __('Email') ?></th>
                        <td><a href="mailto:<?php echo $block->escapeHtml($_order->getCustomerEmail()) ?>"><?php echo $block->escapeHtml($_order->getCustomerEmail()) ?></a></td>
                    </tr>
                    <?php if ($_groupName = $block->getCustomerGroupName()) : ?>
                        <tr>
                            <th><?php /* @escapeNotVerified */ echo __('Customer SBU') ?></th>
                            <td><?php /* @escapeNotVerified */ echo $_groupName ?></td>
                        </tr>
                    <?php endif; ?>
                    <?php foreach ($block->getCustomerAccountData() as $data):?>
                        <tr>
                            <th><?php /* @escapeNotVerified */ echo $data['label'] ?></th>
                            <td><?php /* @escapeNotVerified */ echo $data['value'] ?></td>
                        </tr>
                    <?php endforeach;?>
                </table>
            </div>
        </div>
    </div>
</section>

<section class="admin__page-section order-addresses" style="display: none;">
    <div class="admin__page-section-title">
        <span class="title"><?php /* @escapeNotVerified */ echo __('Information') ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-billing-address">
            <?php /* Billing Address */?>
            <div class="admin__page-section-item-title">
                <span class="title"><?php /* @escapeNotVerified */ echo __('Address') ?></span>
              </div>
            <address class="admin__page-section-item-content"><?php /* @escapeNotVerified */ echo $block->getFormattedAddress($_order->getBillingAddress()); ?></address>
        </div>
      <!--  <?php if (!$block->getOrder()->getIsVirtual()): ?>
            <div class="admin__page-section-item order-shipping-address">
                <?php /* Shipping Address */ ?>
                <div class="admin__page-section-item-title">
                    <span class="title"><?php /* @escapeNotVerified */ echo __('Shipping Address') ?></span>
                 </div>
                <address class="admin__page-section-item-content"><?php /* @escapeNotVerified */ echo $block->getFormattedAddress($_order->getShippingAddress()); ?></address>
            </div>
        <?php endif; ?> -->
    </div>
</section>

<?php
    echo $block->getOrderStatus($_order->getId());
?>

<!--<input style="display:none;" type="text" id="orderid" value="<?php echo $_order->getId(); ?>">
<script type="text/javascript">
require(["jqueryNoConflict"], function(){
    jQuery(document).ready(function (){
        document.getElementById('order-view-cancel-button').style.display = 'none';
        var orderid = document.getElementById('orderid').value;
        console.log(orderid);
    });
});
</script>-->
