<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var  $block \Magento\Sales\Block\Order\View*/?>

<?php		    
//Custom ERP Order Number
$om = \Magento\Framework\App\ObjectManager::getInstance();
$resources = $om->get('Magento\Framework\App\ResourceConnection');
$connection = $resources->getConnection();
							
$query = "SELECT `erpOrderId` FROM `erp_magento` WHERE `magOrderId` = '".$block->getOrder()->getRealOrderId()."'";
$erporder =  $connection->fetchRow($query)['erpOrderId'];
//echo __("<strong>"."Order Reference # ".$erporder."</strong>");
//End /* @escapeNotVerified */ /*$_order->getStatusLabel()*/ id="order_status"
?>
<strong>Delta Order Reference # <?php echo $erporder; ?></strong><br/>
<br/>
<?php $_history = $block->getOrder()->getVisibleStatusHistory() ?>
<?php if (count($_history)): ?>
    <div class="block block-order-details-comments">
        <div class="block-title"><strong><?php /* @escapeNotVerified */ echo __('About Your Order') ?></strong></div>
        <div class="block-content">
            <dl class="order-comments">
                <?php foreach ($_history as $_historyItem): ?>
                    <dt class="comment-date"><?php /* @escapeNotVerified */ echo $block->formatDate($_historyItem->getCreatedAt(), \IntlDateFormatter::MEDIUM, true) ?></dt>
                    <dd class="comment-content"><?php echo $block->escapeHtml($_historyItem->getComment()) ?></dd>
                <?php endforeach; ?>
            </dl>

        </div>
    </div>
<?php endif; ?>
