
<?php

/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<?php

            $om = \Magento\Framework\App\ObjectManager::getInstance();
            $customerSession = $om->get('Magento\Customer\Model\Session');

            $customer_model = $om->create('Magento\Customer\Model\Customer');//->
	  		    $customer_model->setWebsiteId(1);
    		    $customer = $customer_model->load($customerSession->getId());
            $customerData = $customer->getData();

            $companymanagement = $om->create('Magento\Company\Model\CompanyManagement');
            $stp_id = $companymanagement->getByCustomerId($customerSession->getId())->getData("STP_ID");
            $soldtoparty_number = $stp_id;//$customerData['stp_id'];

            $wsdlUrl = dirname(__FILE__)."/wsdl/zcustomercreditinformation_binding.xml";

            //Creat SOAP client instance
            $soapClient  = new \Zend\Soap\Client($wsdlUrl,array("soap_version" => SOAP_1_2));

            try{

            //Set Login details
            $soapClient->setHttpLogin('tmahihlaba');
            $soapClient->setHttpPassword('COMTIA@7');

				     //Set Parameters
            $parameters = array(
                            "Partner" => $soldtoparty_number//"0000000003"//
                            );



            $result      = $soapClient->ZcrmCreditInfo($parameters);
            $optionList  = [];
            $select_o    = '<select name="s_month" class"form-control" id="s_month" >';
            $select_c    = '</select>';


		        /**   GET CUSTOMER STATEMENT **/
		        $wsdlUrl2    = dirname(__FILE__)."/wsdl/zzget_cust_statement_v6_binding.xml";


            if(isset($_POST['s_month'])) {

              $optionList = [];

              $_mo    = $_POST['s_month'] ;
              $_ye    = $_POST['s_year'] ;
              $year   = date("Y");
              $start  = 1;
              $ends   = cal_days_in_month(CAL_GREGORIAN, $_mo , $_ye);
              $fdate  =  '01.'.$_mo.'.'.$_ye ;
              $tdate  =  $ends.'.'.$_mo.'.'.$_ye ;
              $Adate  =  date('d.m.Y');

              $parameters2 = array(
                                 "Adate" => $Adate,
                                 "Bukrs" => '6076',
                                 "Fdate" =>  $fdate,
                                 "Tdate" => $tdate ,
                            "Kunnr" => '1512'//$soldtoparty_number

                            );




              $optionList = setSelected($_mo);
              $_POST      = array();

                //Creat SOAP client instance
            $soapClient2  = new \Zend\Soap\Client($wsdlUrl2,array("soap_version" => SOAP_1_2));

            //Set Login details
            $soapClient2->setHttpLogin('tmahihlaba');
            $soapClient2->setHttpPassword('COMTIA@7');

            $tab_result   = $soapClient2->ZzcustomerStatementPdf($parameters2);





            $data         = base64_encode($tab_result->Pdf);
            $data         = 'data:application/pdf;base64,'.$data;




            }else{
                $_POST     = array();
               $optionList = setSelected('');
            }
         }catch (Exception $ex) {
            //var_dump($ex);
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $redirect = $objectManager->get('\Magento\Framework\App\Response\Http');
            $redirect->setRedirect('customer/Account/index');
       }

             function setSelected($line){

                $optionList = [];

                if($line != '')
                {
                    $_month = getMonth($line);
                    $option = "<option value='".$line."' selected>".$_month."</option>";

                    array_push($optionList,$option);

                    for ($x = 1 ;$x<=11 ; $x++) {

                    $_month = getMonth($x);
                    if($x <= 9){
                     $_mo = '0'.$x ;
                    }else{
                       $_mo  = $x  ;
                    }

                    $option = "<option value='".$_mo."'>".$_month."</option>";
                    array_push($optionList,$option);

                }
                $line = '';
                $_POST['s_month'] = '';

            }else{

                for ($x = 1 ;$x<=12 ; $x++){

                 $_month = getMonth($x);
                 if($x <= 9){
                     $_mo = '0'.$x ;
                    }else{
                       $_mo  = $x  ;
                    }
                 $option = "<option value='".$_mo."'>".$_month."</option>";
                 array_push($optionList,$option);

                }



            }


        return $optionList;
        }




       function getMonth($x){
                $monthName = date("F", mktime(0, 0, 0, $x, 10));
                //var_dump($monthName);
               return $monthName ;


        }



            ?>
<!--<div class="block block-balance">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Balance'); ?></strong>
    </div>
    <div class="block-content">
        <p>
            <span class="balance-price-label"><?php /* @escapeNotVerified */ echo __('Licence Number:'); ?></span>
            <?php /* @escapeNotVerified */echo $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($block->getBalance()); ?>
        </p>
    </div>
</div>-->

<div class="block block-balance">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Credit Limit'); ?></strong>
    </div>
    <div class="block-content">
        <p>
            <span class="balance-price-label"><?php /* @escapeNotVerified */ echo __('Credit Limit'); ?></span>
            <?php /* @escapeNotVerified */ echo($this->helper('Magento\Framework\Pricing\Helper\Data')->currency($result->ExCredInfo->item->LvCredLim)); ?>
        </p>
    </div>
</div>

<div class="block block-balance">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Balance:'); ?></strong>
    </div>
    <div class="block-content">
        <p>
            <span class="balance-price-label"><?php /* @escapeNotVerified */ echo __('Balance:'); ?></span>
            <?php /* @escapeNotVerified */ echo($this->helper('Magento\Framework\Pricing\Helper\Data')->currency($result->ExCredInfo->item->LvCredBal)); ?>
        </p>
    </div>
</div>

<div class="block block-balance">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Last Pay:'); ?></strong>
    </div>
    <div class="block-content">
        <p>
            <span class="balance-price-label"><?php /* @escapeNotVerified */ echo __('Last Pay:'); ?></span>
            <?php /* @escapeNotVerified */ echo($this->helper('Magento\Framework\Pricing\Helper\Data')->currency($result->ExCredInfo->item->LvLastPay)); ?>
        </p>
    </div>
</div>


<div class="block">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */ echo __('Account Statement: ');?></strong></div>

        <div class="bootstrap-iso">
          <link rel="stylesheet" type="text/css" href="<?php echo '../../../../resources/bootstrap/css/bootstrap-iso.css';?>">

        <form class="form-inline" id="f_month" action="" method="POST">
         <div class="form-group">

             <label for="s_year">Year </label>
             <input type="numer" class="form-control" name="s_year" id="s_year" value="2016">
       
        </div>

        <div class="form-group">
           
            <?php

           echo $select_o;
            foreach ($optionList as $opt) {
               echo $opt ;
            }
            echo $select_c;

        ?>
        </div>
      
        </form>
      

   
    <div class="block-content">
        <div class="container">
           <div class="jumbotron">
                 <iframe src="<?php  if (isset($data)) echo $data ?>" style="width:100%; height:300px;" frameborder="0"></iframe>
          </div>
        </div>
    </div>
    </div>
</div>


<script >
    require(['jquery', 'jquery/ui'], function($){
        //your js code here



        $("#s_month").change(function(e) {
              //e.preventDefault();
            var _MO = $("#s_month :selected").val();      

            //$.ajax({
            // type: 'POST',
              //   url: <?php// echo "'".$_SERVER['REQUEST_URI']."'"; ?>,
              //  data: {'month': _MO },
              //  });

           // _mo = '';

            $("#f_month").submit();

        });

    });
</script>
<script type="text/javascript">
  require(["bootstrap3"], function(){
   });
</script>

