<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var $block \Magento\Catalog\Block\Catalog\Product\View\Addto\Compare */
?>
<div style="display:none">
	<a href="#" data-post='<?= /* @escapeNotVerified */ $block->getPostDataParams() ?>'
		data-role="add-to-links"
		class="action tocompare"><span><?= /* @escapeNotVerified */ __('Add to Compare') ?></span></a>
</div>
