<table>
    <tr>
        <td>Product ID</td>
        <td>Promotion </td>
        <td>Creation Time</td> 
        <td>Update Time</td> 
        <td>Valid from</td> 	
        <td>Valid To</td>
    </tr>
    <?php foreach ($block->getDemoItems() as $item): ?>
        <tr>
            <td><?php echo $item->getId(); ?></td>
            <td><?php echo $item->getTitle(); ?></td>

            <td><?php echo $item->getCreation_time(); ?> </td>
            <td><?php echo $item->getUpdate_time(); ?></td>

            <td><?php echo $item->getBotext_DescriptionOfAgreement(); ?></td>
                <td><?php echo $item->getKnumh_ConditionRecordNumber(); ?> </td>
        </tr>
    <?php endforeach; ?>
</table>
<p><?php echo $block->getHeader(); ?></p>


<hr>

