<h1>test</h1> 

<table class="table">
    <thead class="thead-default">
        <tr>
            <th>#</th>
            <th>Promotion</th>
            <th>Title</th>
            <th>Valid from</th>
            <th>Valid To</th>
            <th>Description of Agreement</th>
            <th>Product</th>
        </tr>
    </thead>
    <tbody>

        <?php foreach ($block->getPromoItems() as $item): ?>
            <tr> <th scope="row"><?php echo $item->getId(); ?> </th>
               
                
                <td><?php echo $item->getKnuma_promo(); ?></td>
                <td><?php echo $item->getTitle(); ?></td>

                <td><?php echo $item->getDatab_aggreementValidFrom(); ?> </td>
                <td><?php echo $item->getDatbi_AgreementValidTo(); ?></td>

                <td><?php echo $item->getVkorg_salesorg(); ?></td>
                <td><?php echo $item->getMatnr(); ?> </td>
            </tr>
        <?php endforeach; ?>
         


    </tbody>
</table>